#!/usr/bin/env python3
"""Regenerate docs/research/ETF_SCREEN_TABLE.md — the durable, human-readable results
table for the 311-ETF Wang-pipeline screen (user directive 2026-06-11: keep a results
table, committed each round).

Joins results/etf_screen.csv (per-ETF best-mechanism verdicts, regenerated by
screen_report.py) against the full universe (results/etf_qc_confirmed_pre2009.csv) so
PENDING names are visible. Sorted: STRONG > marginal > NO-FIT > ARTIFACT > NO-BASELINE
> PENDING; by edge desc within group.

  python3 scripts/research/screen_table.py
"""
import csv
from datetime import datetime, timezone

from lb.paths import ROOT, RESULTS_DIR

UNIVERSE = str(RESULTS_DIR / "etf_qc_confirmed_pre2009.csv")
SCREEN = str(RESULTS_DIR / "etf_screen.csv")
OUT = str(ROOT / "docs" / "research" / "ETF_SCREEN_TABLE.md")

_ORDER = {"VERIFIED": -1, "STRONG": 0, "FRAGILE": 1, "marginal": 1, "NO-FIT": 2,
          "REFUTED": 3, "ARTIFACT": 3, "NO-BASELINE": 4, "PENDING": 5}

# GATE ADJUDICATIONS (2026-06-12 sweeps) — override the screen verdict with the
# permute+re-race outcome. The screen is admission; this column is the trial record.
ADJUDICATED = {
    "GLD": "VERIFIED (crown 4.70 lgbm_bag+vae)", "USO": "VERIFIED (2.82)",
    "DIA": "VERIFIED (1.66)", "DXJ": "VERIFIED (1.85)",
    "IAU": "VERIFIED-family (gold-trend replication)",
    "IJR": "AUDITS-PASS, ONLINE-FAIL (2.51 vs BH 0.43, +2.09 edge, permute/regime/deflated all PASS; preds_match=0 diff 0.136 — NOT deployable until online divergence root-caused; DIA same recipe passes 8e-09)",
    "EWZ": "FRAGILE (permute-pass, one-regime)", "UGL": "FRAGILE (permute-pass, one-regime)",
    "FEZ": "FRAGILE (one-regime + deflated-fail)", "IAT": "FRAGILE (watchlist)",  # IAI changept recipe separately refuted 2026-06-12
    "PRFZ": "FRAGILE (replication-failed)",
    "EWT": "REFUTED (stale 5.13->0.04)", "EWL": "REFUTED (stale)", "IDV": "REFUTED (stale)",
    "AAXJ": "REFUTED (stale)", "VT": "REFUTED (stale)", "EWG": "REFUTED (no label signal)",
    "IXG": "REFUTED (stale)", "EWY": "REFUTED (stale)", "ILF": "REFUTED (stale)",
    "EPP": "REFUTED (overlay artifact, permute 57%)",
    # Core names (pre-screen, adjudicated by ~2500 tournament rounds — the PENDING was a join artifact):
    "SPY": "BH-OPTIMAL (closed every door incl options-IV)", "QQQ": "BH-OPTIMAL (action bracket)",
    "IWM": "BH-OPTIMAL (seat)", "SLV": "BH-OPTIMAL", "HYG": "BH-OPTIMAL (seat 1.97)",
    "TLT": "NO-EDGE (closed)", "XLE": "ceiling 1.35 (closed)", "EEM": "BH-OPTIMAL (timing decayed)",
    "EFA": "BH-OPTIMAL", "SOXX": "REFUTED (leak-era edge gone)", "KRE": "NO-EDGE (Bonferroni-fail)",
    "XBI": "NO-EDGE (event-driven)", "XME": "predictable-not-profitable (+0.04)",
    "TIP": "BH-OPTIMAL (seat)", "ITB": "NO-EDGE (Bonferroni-fail)", "DBC": "BH-OPTIMAL (seat)",
    "FXY": "NO-EDGE", "MGK": "BH-OPTIMAL", "VOE": "BH-OPTIMAL",
    "QLD": "REFUTED (stale 4.06->-0.05, permute>real)",
    "GDX": "REFUTED (stale 2.48->-0.08, permute>real; gold-trend does NOT extend to miners)",
    "AGQ": "REFUTED (stale 2.49->0.07)",
    "EPI": "REFUTED (stale 1.11->0.11; val_auc collapsed 0.85->0.36)",
    "DJP": "REFUTED (permute 0.85 > real 0.75 — label-free)",
    "GSG": "REFUTED (stale 1.92->-0.01)",
    "FXZ": "REFUTED (stale 1.07->0.15, permute==real, auc 0.48)",
    "VDE": "REFUTED (stale 1.47->0.24, permute 0.36 > real; auc 0.93->0.51)",
    "EWW": "REFUTED (stale 1.01->0.02)",
    "FCG": "REFUTED (stale 1.06->0.37 < BH; auc 0.47)",
    "IAI": "REFUTED (changept 0.32 < permute 0.43)",
    "IGE": "REFUTED (0.35, permute 0.24 = 70% of real — gate fail; stale 1.0x)",
    "VWO": "REFUTED (real leg degenerate 0 trades, auc 0.50)",
}


def _group(verdict):
    for k in _ORDER:
        if verdict.startswith(k):
            return k
    return verdict or "PENDING"


def main():
    uni = {r["Ticker"].strip(): r for r in csv.DictReader(open(UNIVERSE)) if r.get("Ticker", "").strip()}
    screened = {}
    for r in csv.DictReader(open(SCREEN)):
        if r.get("ticker") and r["ticker"] != "ticker":
            screened[r["ticker"].strip()] = r

    rows = []
    for tk, u in uni.items():
        s = screened.get(tk)
        if s:
            rows.append({"tk": tk, "cls": s["asset_class"], "recipe": s["recipe"],
                         "mc": float(s["method_calmar"] or 0), "bh": float(s["buyhold_calmar"] or 0),
                         "edge": float(s["edge"] or 0), "auc": float(s["val_auc"] or 0),
                         "tr": int(float(s["trades"] or 0)), "verdict": ADJUDICATED.get(tk, s["verdict"]),
                         "name": (s.get("name") or u.get("Name", ""))[:40]})
        else:
            rows.append({"tk": tk, "cls": u.get("Asset_Class", ""), "recipe": "—", "mc": None,
                         "bh": None, "edge": None, "auc": None, "tr": None, "verdict": ADJUDICATED.get(tk, "PENDING"),
                         "name": u.get("Name", "")[:40]})

    rows.sort(key=lambda r: (_ORDER.get(_group(r["verdict"]), 9),
                             -(r["edge"] if r["edge"] is not None else -999)))
    counts = {}
    for r in rows:
        counts[_group(r["verdict"])] = counts.get(_group(r["verdict"]), 0) + 1

    def num(v, fmt="{:.2f}"):
        return fmt.format(v) if v is not None else "—"

    lines = [
        "# 311-ETF screen — results table",
        "",
        f"_Auto-regenerated by `scripts/research/screen_table.py` · "
        f"{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} · updated each loop round._",
        "",
        f"**Coverage: {len(screened)}/{len(uni)} screened.** Verdicts: "
        + " · ".join(f"{k} {counts.get(k, 0)}" for k in _ORDER),
        "",
        "Per ETF: best mechanism from the screen panel (trend/regime/ker/changepoint/sadf) vs the "
        "name's OWN buy-hold. `edge = method − buyhold` Calmar. A row is only a LEAD after the "
        "keep-gates (permute/DSR/decay) — see program.md; the screen verdict is admission, not crown.",
        "",
        "| ticker | class | best recipe | method | buy-hold | edge | val_auc | trades | verdict | name |",
        "|---|---|---|---:|---:|---:|---:|---:|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['tk']} | {r['cls'][:12]} | {r['recipe']} | {num(r['mc'])} | {num(r['bh'])} "
            f"| {num(r['edge'], '{:+.2f}')} | {num(r['auc'])} | {r['tr'] if r['tr'] is not None else '—'} "
            f"| {r['verdict']} | {r['name']} |")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT}: {len(rows)} rows ({len(screened)} screened, "
          f"{len(uni) - len(screened)} pending)")


if __name__ == "__main__":
    main()
